# Generated by Django 3.0.14 on 2021-12-30 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datatime', models.DateTimeField()),
                ('summary', models.CharField(max_length=80)),
                ('description', models.TextField(null=True)),
                ('tags', models.CharField(choices=[('DRIVE', '드라이브'), ('MEAL', '식사')], max_length=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
