# Generated by Django 3.0.14 on 2021-12-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_datatime',
            new_name='end_datetime',
        ),
    ]
